### ISSUE TITLE
no obvious way to select sensors in historical

### ISSUE THREAD

**Issue by jbclements** [cal-poly-solar-decathlon/sodec-js-app#13]
When I choose "humidity", I can't see anything besides "bedroom". I think we need a drop-down for this?

**Comment by bommysk** [comment]
When you hover over humidity you should see a dropdown immediately, are you able to see the dropdown for temperature?

**Comment by jbclements** [comment]
Oh! I see it now. Strange that I didn't see it before... Let's see if others notice this issue. Closing this for now.
